---
version: '3.7'
services:
    client:
      image: bobcrutchley/quad-client:latest
      build:
        context: ./client
      depends_on:
        - server
        - jenkins
      ports:
      - target: 80
        published: 80
        protocol: tcp
    server:
      image: bobcrutchley/quad-server:latest
      build:
        context: ./server
      depends_on:
        - mongo
    jenkins:
      image: bobcrutchley/jenkins:latest
      environment:
        - JENKINS_OPTS="--prefix=/jenkins"
      volumes:
        - type: volume
          source: jenkins-home
          target: /var/jenkins_home
        - type: bind
          source: /var/run/docker.sock
          target: /var/run/docker.sock
    mongo:
      image: mongo
      volumes:
        - type: volume
          source: mongo
          target: /data/db
volumes:
  jenkins-home:
  mongo:
